package com.advocatediary.view;


import com.advocatediary.model.AdvocateDiaryModel;
import com.advocatediary.controller.algorithms.SelectionSort;
import com.advocatediary.controller.algorithms.InsertionSort;
import com.advocatediary.controller.algorithms.MergeSort;
import com.advocatediary.controller.algorithms.BinarySearch;
import com.advocatediary.util.ValidationUtil;
import java.awt.Dimension;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PragyaRayamajhi 23048659
 */
public class AdvocateDiary extends javax.swing.JFrame {

    private List<AdvocateDiaryModel> caseList;
    private java.awt.CardLayout cardLayout;
    private final ValidationUtil validationUtil;

    /**
     * Creates new form CollegeApp
     */
    public AdvocateDiary() {
        setResizable(false);
        initComponents();
        validationUtil = new ValidationUtil();
        initializeLayout(); // Set up CardLayout and add screens
        initializeData(); // Initialize case data and table
        startProgress(); // Show loading screen and initiate progress       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainScreen = new javax.swing.JPanel();
        pnlMainBar = new javax.swing.JPanel();
        lblMainBarSlogan = new javax.swing.JLabel();
        lblMainBarLogo = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        pnlSolutions = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        lblHomeText = new javax.swing.JLabel();
        lblHomeTextDescription = new javax.swing.JLabel();
        btnLearnMore = new javax.swing.JButton();
        lblHomeScreen = new javax.swing.JLabel();
        pnlAboutUs = new javax.swing.JPanel();
        lblSnehalTitle = new javax.swing.JLabel();
        lblSnehalSub = new javax.swing.JLabel();
        lblPragyaTitle = new javax.swing.JLabel();
        lblPragyaSub = new javax.swing.JLabel();
        lblSuyeshTitle = new javax.swing.JLabel();
        lblSuyeshSub = new javax.swing.JLabel();
        lblContactUs = new javax.swing.JLabel();
        lblContactPart1 = new javax.swing.JLabel();
        lblInformation = new javax.swing.JLabel();
        lblPragyaImage = new javax.swing.JLabel();
        lblSnehalImage = new javax.swing.JLabel();
        lblSuyeshImage = new javax.swing.JLabel();
        pnlDashboard = new javax.swing.JPanel();
        spTblStudent = new javax.swing.JScrollPane();
        tblCase = new javax.swing.JTable();
        lblTblStudentTitle = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        cmbType = new javax.swing.JComboBox<>();
        txtCaseId = new javax.swing.JTextField();
        txtAssignedLawyer = new javax.swing.JTextField();
        txtCaseName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblErrorMessage = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        txtCourtName = new javax.swing.JTextField();
        txtFilingDate = new javax.swing.JTextField();
        txtClientName = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmbSortBy = new javax.swing.JComboBox<>();
        cmbSelectionSortingOrder = new javax.swing.JComboBox<>();
        btnSearchBy = new javax.swing.JButton();
        txtSearchValue = new javax.swing.JTextField();
        pnlLegalSolutions = new javax.swing.JPanel();
        txtSolutionsTittle = new javax.swing.JLabel();
        lblCivilCase = new javax.swing.JLabel();
        lblCivilCasesDescription = new javax.swing.JLabel();
        lblCorporateCases = new javax.swing.JLabel();
        CorporateCasesDescription = new javax.swing.JLabel();
        lblIntellectualPropertyCases = new javax.swing.JLabel();
        PropertyCasesDescription = new javax.swing.JLabel();
        lblConsumerProtectionCases = new javax.swing.JLabel();
        lblConsumerProtectionCasesDescription = new javax.swing.JLabel();
        lblEstateProbateCases = new javax.swing.JLabel();
        lblEstateAndProbateCases = new javax.swing.JLabel();
        LblTechnologyAndCyberLawCases = new javax.swing.JLabel();
        lblTechnologyCaseDescription = new javax.swing.JLabel();
        lblLegalSolutionsImage = new javax.swing.JLabel();
        pnlLoginScreen = new javax.swing.JPanel();
        txtFldLoginUsername = new javax.swing.JTextField();
        pwdFldLogin = new javax.swing.JPasswordField();
        lblLoginForgotPwd = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        lblLoginError = new javax.swing.JLabel();
        lblLoginImage = new javax.swing.JLabel();
        pwdFldLogin1 = new javax.swing.JPasswordField();
        lblLoginMessage = new javax.swing.JLabel();
        pnlLoadingScreen = new javax.swing.JPanel();
        pgBarSplashScreen = new javax.swing.JProgressBar(0,100);
        lblLoading = new javax.swing.JLabel();
        lblWelcomeTitle = new javax.swing.JLabel();
        lblLoadingPageImage = new javax.swing.JLabel();

        pnlMainScreen.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainScreen.setMaximumSize(new java.awt.Dimension(1140, 650));
        pnlMainScreen.setMinimumSize(new java.awt.Dimension(1140, 650));
        pnlMainScreen.setPreferredSize(new java.awt.Dimension(1140, 650));

        pnlMainBar.setBackground(new java.awt.Color(230, 218, 186));

        lblMainBarSlogan.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        lblMainBarSlogan.setText("Perfect Legal partner for people and organizations.");

        lblMainBarLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/collegeapp/resources/advocateLogo.png"))); // NOI18N

        btnLogout.setBackground(new java.awt.Color(214, 167, 105));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainBarLayout = new javax.swing.GroupLayout(pnlMainBar);
        pnlMainBar.setLayout(pnlMainBarLayout);
        pnlMainBarLayout.setHorizontalGroup(
            pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainBarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMainBarLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169)
                .addComponent(lblMainBarSlogan, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        pnlMainBarLayout.setVerticalGroup(
            pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMainBarSlogan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainBarLayout.createSequentialGroup()
                        .addGroup(pnlMainBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMainBarLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        pnlSolutions.setBackground(new java.awt.Color(158, 135, 104));
        pnlSolutions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32), 0));
        pnlSolutions.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));
        pnlHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32)));
        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHomeText.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblHomeText.setText("<html>You need expert legal<br>advice.<html>");
        pnlHome.add(lblHomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 508, 160));

        lblHomeTextDescription.setFont(new java.awt.Font("Helvetica Neue", 0, 19)); // NOI18N
        lblHomeTextDescription.setText("<html>We're a Kathmandu-based legal service provider<br>always available to connect you with the right<br> advocate through our advocate management system<br> to help with anything on your legal matters.<html>");
        pnlHome.add(lblHomeTextDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 601, 137));

        btnLearnMore.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnLearnMore.setText("Explore More");
        btnLearnMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLearnMoreActionPerformed(evt);
            }
        });
        pnlHome.add(btnLearnMore, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, -1, 30));

        lblHomeScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/collegeapp/resources/home page.jpeg"))); // NOI18N
        pnlHome.add(lblHomeScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 1130, 600));

        pnlSolutions.addTab("Home", pnlHome);

        pnlAboutUs.setBackground(new java.awt.Color(219, 214, 198));
        pnlAboutUs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32)));

        lblSnehalTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblSnehalTitle.setText("Snehal Subedi");

        lblSnehalSub.setText("Founder");

        lblPragyaTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPragyaTitle.setText("Pragya Rayamajhi");

        lblPragyaSub.setText("Managing Director");

        lblSuyeshTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblSuyeshTitle.setText("Suyesh Neupane");

        lblSuyeshSub.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        lblSuyeshSub.setText("CEO");

        lblContactUs.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblContactUs.setText(" Contact Us Today");

        lblContactPart1.setText("<html>Main Office<br> Maitidevi, Kathmandu</html>");

        lblInformation.setText("<html>Tel: 071-560709<br>\nEmail: advocatediary@gmail.com<br>\nSocial: @advocatediary</html>");

        lblPragyaImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/collegeapp/resources/pragya.jpeg"))); // NOI18N

        lblSnehalImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/collegeapp/resources/snehal.jpeg"))); // NOI18N

        lblSuyeshImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/collegeapp/resources/suyesh.jpeg"))); // NOI18N

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblPragyaTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblPragyaImage)
                            .addComponent(lblContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(lblSnehalSub, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblPragyaSub, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207)
                        .addComponent(lblSuyeshSub, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(lblSnehalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContactPart1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSnehalImage, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(160, 160, 160)
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSuyeshImage)
                            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblSuyeshTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPragyaImage)
                            .addComponent(lblSnehalImage))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutUsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSuyeshImage, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPragyaTitle)
                    .addComponent(lblSnehalTitle)
                    .addComponent(lblSuyeshTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSnehalSub)
                            .addComponent(lblPragyaSub))
                        .addGap(18, 18, 18)
                        .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblContactUs, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblContactPart1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblSuyeshSub))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pnlSolutions.addTab("About Us", pnlAboutUs);

        pnlDashboard.setBackground(new java.awt.Color(219, 214, 198));

        tblCase.setBackground(new java.awt.Color(163, 153, 139));
        tblCase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Case ID", "Case Name", "Case Type", "Assigned Lawyer", "Case Status", "Court Name", "Filing Date", "Client Name", "Contact No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCase.setGridColor(new java.awt.Color(0, 0, 0));
        tblCase.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblCase.setSelectionForeground(new java.awt.Color(234, 192, 32));
        tblCase.setShowGrid(true);
        tblCase.getTableHeader().setReorderingAllowed(false);
        tblCase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCaseMouseClicked(evt);
            }
        });
        spTblStudent.setViewportView(tblCase);
        if (tblCase.getColumnModel().getColumnCount() > 0) {
            tblCase.getColumnModel().getColumn(0).setResizable(false);
            tblCase.getColumnModel().getColumn(1).setResizable(false);
            tblCase.getColumnModel().getColumn(2).setResizable(false);
            tblCase.getColumnModel().getColumn(3).setResizable(false);
            tblCase.getColumnModel().getColumn(4).setResizable(false);
            tblCase.getColumnModel().getColumn(4).setPreferredWidth(40);
            tblCase.getColumnModel().getColumn(5).setResizable(false);
            tblCase.getColumnModel().getColumn(6).setResizable(false);
            tblCase.getColumnModel().getColumn(7).setResizable(false);
            tblCase.getColumnModel().getColumn(8).setResizable(false);
        }

        lblTblStudentTitle.setBackground(new java.awt.Color(234, 192, 32));
        lblTblStudentTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTblStudentTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblTblStudentTitle.setText("Case Information");

        cmbStatus.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Open", "Closed", "Pending", " ", " " }));
        cmbStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Case status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });

        cmbType.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil", "Criminal", "Bankruptcy", "Family" }));
        cmbType.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CaseType", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        cmbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTypeActionPerformed(evt);
            }
        });

        txtCaseId.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtCaseId.setForeground(new java.awt.Color(51, 51, 51));
        txtCaseId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CaseID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        txtCaseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaseIdActionPerformed(evt);
            }
        });

        txtAssignedLawyer.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtAssignedLawyer.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Assigned Lawyer", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N

        txtCaseName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtCaseName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CaseName", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        txtCaseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaseNameActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(196, 237, 190));
        btnAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(176, 165, 168));
        btnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(217, 133, 161));
        btnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(245, 232, 174));
        btnClear.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtCourtName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtCourtName.setForeground(new java.awt.Color(51, 51, 51));
        txtCourtName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CourtName", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        txtCourtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCourtNameActionPerformed(evt);
            }
        });

        txtFilingDate.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtFilingDate.setForeground(new java.awt.Color(51, 51, 51));
        txtFilingDate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filing Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        txtFilingDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilingDateActionPerformed(evt);
            }
        });

        txtClientName.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtClientName.setForeground(new java.awt.Color(51, 51, 51));
        txtClientName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        txtClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientNameActionPerformed(evt);
            }
        });

        txtContactNo.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtContactNo.setForeground(new java.awt.Color(51, 51, 51));
        txtContactNo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contact No", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N
        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Sort");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbSortBy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CaseID", "CaseName", "Assigend Lawyer" }));
        cmbSortBy.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sorted By", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        cmbSelectionSortingOrder.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));
        cmbSelectionSortingOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Sorting Order", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnSearchBy.setBackground(new java.awt.Color(255, 204, 204));
        btnSearchBy.setText("Search");
        btnSearchBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByActionPerformed(evt);
            }
        });

        txtSearchValue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter a value", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        txtSearchValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDashboardLayout = new javax.swing.GroupLayout(pnlDashboard);
        pnlDashboard.setLayout(pnlDashboardLayout);
        pnlDashboardLayout.setHorizontalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDashboardLayout.createSequentialGroup()
                                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCaseId, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCourtName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFilingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                                        .addComponent(txtAssignedLawyer, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 7, Short.MAX_VALUE)))
                        .addGap(14, 14, 14))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDashboardLayout.createSequentialGroup()
                                .addComponent(lblTblStudentTitle)
                                .addGap(293, 293, 293)
                                .addComponent(cmbSortBy, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addComponent(cmbSelectionSortingOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spTblStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 1066, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(238, 238, 238)
                .addComponent(btnSearchBy)
                .addGap(105, 105, 105))
        );
        pnlDashboardLayout.setVerticalGroup(
            pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDashboardLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnSearchBy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbSelectionSortingOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSortBy)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTblStudentTitle)
                            .addComponent(txtSearchValue, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTblStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDashboardLayout.createSequentialGroup()
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCaseId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAssignedLawyer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(pnlDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFilingDate, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCourtName, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)))
                .addComponent(lblErrorMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlSolutions.addTab("Admin Dashboard", pnlDashboard);

        txtSolutionsTittle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        txtSolutionsTittle.setText("<html>Our support<br>services</html>");

        lblCivilCase.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCivilCase.setText("Civil Cases");

        lblCivilCasesDescription.setText("<html>Contrsct didputes,Family law,Land and<br>property Disputes.</html>");

        lblCorporateCases.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblCorporateCases.setText("Corporate Cases");

        CorporateCasesDescription.setText("Employment disputes,intellectual property");

        lblIntellectualPropertyCases.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblIntellectualPropertyCases.setText("Property Cases");

        PropertyCasesDescription.setText("Licensing agreements and IP theft");

        lblConsumerProtectionCases.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblConsumerProtectionCases.setText("Consumer Protection Cases");

        lblConsumerProtectionCasesDescription.setText("<html>Cases involving unfair trade practices,<br>defective goods, or misleading advertising</html>");

        lblEstateProbateCases.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblEstateProbateCases.setText("Estate and Probate Cases");

        lblEstateAndProbateCases.setText("Wills and Trusts,Guardianship");

        LblTechnologyAndCyberLawCases.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        LblTechnologyAndCyberLawCases.setText("Technology and cyber law cases");

        lblTechnologyCaseDescription.setText("<html>Data breaches, cybercrimes, and online<br>defamation.</html>");

        lblLegalSolutionsImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/collegeapp/resources/legalsolutions.jpeg"))); // NOI18N

        javax.swing.GroupLayout pnlLegalSolutionsLayout = new javax.swing.GroupLayout(pnlLegalSolutions);
        pnlLegalSolutions.setLayout(pnlLegalSolutionsLayout);
        pnlLegalSolutionsLayout.setHorizontalGroup(
            pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLegalSolutionsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtSolutionsTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlLegalSolutionsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblLegalSolutionsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLegalSolutionsLayout.createSequentialGroup()
                        .addComponent(lblEstateAndProbateCases)
                        .addGap(235, 235, 235)
                        .addComponent(lblTechnologyCaseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLegalSolutionsLayout.createSequentialGroup()
                        .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCivilCase)
                            .addComponent(lblCivilCasesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIntellectualPropertyCases)
                            .addComponent(PropertyCasesDescription)
                            .addComponent(lblEstateProbateCases))
                        .addGap(212, 212, 212)
                        .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblTechnologyAndCyberLawCases)
                            .addComponent(lblConsumerProtectionCases)
                            .addComponent(lblConsumerProtectionCasesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CorporateCasesDescription)
                            .addComponent(lblCorporateCases))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        pnlLegalSolutionsLayout.setVerticalGroup(
            pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLegalSolutionsLayout.createSequentialGroup()
                .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLegalSolutionsLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(txtSolutionsTittle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblLegalSolutionsImage, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLegalSolutionsLayout.createSequentialGroup()
                        .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLegalSolutionsLayout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(lblCorporateCases))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLegalSolutionsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblCivilCase)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CorporateCasesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCivilCasesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIntellectualPropertyCases)
                            .addComponent(lblConsumerProtectionCases))
                        .addGap(17, 17, 17)
                        .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblConsumerProtectionCasesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PropertyCasesDescription))
                        .addGap(38, 38, 38)
                        .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstateProbateCases)
                            .addComponent(LblTechnologyAndCyberLawCases))
                        .addGap(9, 9, 9)
                        .addGroup(pnlLegalSolutionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTechnologyCaseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstateAndProbateCases))))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pnlSolutions.addTab("Legal Solutions", pnlLegalSolutions);

        javax.swing.GroupLayout pnlMainScreenLayout = new javax.swing.GroupLayout(pnlMainScreen);
        pnlMainScreen.setLayout(pnlMainScreenLayout);
        pnlMainScreenLayout.setHorizontalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMainBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlSolutions)
                .addContainerGap())
        );
        pnlMainScreenLayout.setVerticalGroup(
            pnlMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainScreenLayout.createSequentialGroup()
                .addComponent(pnlMainBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSolutions))
        );

        pnlLoginScreen.setBackground(new java.awt.Color(219, 215, 198));
        pnlLoginScreen.setMaximumSize(new java.awt.Dimension(1140, 650));
        pnlLoginScreen.setMinimumSize(new java.awt.Dimension(1140, 650));
        pnlLoginScreen.setPreferredSize(new java.awt.Dimension(1140, 650));
        pnlLoginScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFldLoginUsername.setBackground(new java.awt.Color(153, 129, 104));
        txtFldLoginUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32), 0), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        txtFldLoginUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldLoginUsernameActionPerformed(evt);
            }
        });
        pnlLoginScreen.add(txtFldLoginUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 262, 59));

        pwdFldLogin.setBackground(new java.awt.Color(153, 129, 104));
        pwdFldLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32), 0), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pwdFldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFldLoginActionPerformed(evt);
            }
        });
        pnlLoginScreen.add(pwdFldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 262, 59));

        lblLoginForgotPwd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoginForgotPwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginForgotPwd.setText("Forgot your password?");
        pnlLoginScreen.add(lblLoginForgotPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 464, -1));

        btnLogin.setBackground(new java.awt.Color(48, 36, 23));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlLoginScreen.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 260, 50));

        lblLoginError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoginError.setForeground(new java.awt.Color(255, 0, 0));
        lblLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pnlLoginScreen.add(lblLoginError, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 464, 20));

        lblLoginImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/collegeapp/resources/loginpragya.jpg"))); // NOI18N
        pnlLoginScreen.add(lblLoginImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 700));

        pwdFldLogin1.setBackground(new java.awt.Color(153, 129, 104));
        pwdFldLogin1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32), 0), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        pwdFldLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFldLogin1ActionPerformed(evt);
            }
        });
        pnlLoginScreen.add(pwdFldLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 262, 59));

        lblLoginMessage.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLoginMessage.setText("LOGIN to your account");
        pnlLoginScreen.add(lblLoginMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 80, 270, 60));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1140, 650));
        setSize(new java.awt.Dimension(1140, 650));

        pnlLoadingScreen.setBackground(new java.awt.Color(219, 214, 198));
        pnlLoadingScreen.setMaximumSize(new java.awt.Dimension(1140, 600));
        pnlLoadingScreen.setMinimumSize(new java.awt.Dimension(1140, 600));
        pnlLoadingScreen.setPreferredSize(new java.awt.Dimension(1140, 600));
        pnlLoadingScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pgBarSplashScreen.setStringPainted(true);
        pgBarSplashScreen.setForeground(new java.awt.Color(0, 0, 0));
        pnlLoadingScreen.add(pgBarSplashScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 385, 31));

        lblLoading.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLoading.setText("Loading...");
        pnlLoadingScreen.add(lblLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, -1, 30));

        lblWelcomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        lblWelcomeTitle.setText("Welcome to Advocate Diary");
        pnlLoadingScreen.add(lblWelcomeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 330, 61));

        lblLoadingPageImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/collegeapp/resources/loadingPage.png"))); // NOI18N
        pnlLoadingScreen.add(lblLoadingPageImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 640, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Initializes the layout of the application by setting up the CardLayout
     * and adding panels for different screens. Each panel is uniquely
     * identified for easy navigation between screens.
     */
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(pnlLoadingScreen, "LoadingScreen");
        getContentPane().add(pnlLoginScreen, "LoginScreen");
        getContentPane().add(pnlMainScreen, "MainScreen");

        // Start with the loading screen
        loadScreen("LoadingScreen");
    }

    /**
     * Initializes the application's data, including the case list and table.
     * Populates the case list with sample data for demonstration purposes.
     */
        private void initializeData() {
        caseList = new LinkedList<>();

        // Create a table model with column names
        DefaultTableModel model = new DefaultTableModel(
            new Object[][]{}, // No initial data
            new String[]{ // Column names
                "Case ID", "Case Name", "Case Type", "Assigned Lawyer", "Case Status", 
                "Court Name", "Filing Date", "Client Name", "Contact No"
            }
        );
        tblCase.setModel(model);

        // Example data for the table
        registerCase(new AdvocateDiaryModel(10001, "Property Dispute", "Civil", "John Doe", "Open", "District Court", "10-01-2023", "Alice Johnson", "9812345678"));
        registerCase(new AdvocateDiaryModel(10002, "Fraud Investigation", "Criminal", "Jane Smith", "In Progress", "Supreme Court", "15-02-2023", "Bob Martin", "9809876543"));
        registerCase(new AdvocateDiaryModel(10003, "Contract Breach", "Civil", "Emily Davis", "Closed", "High Court", "20-03-2023", "Michael Brown", "9876543210"));
        registerCase(new AdvocateDiaryModel(10004, "Theft Case", "Criminal", "Daniel Wilson", "Open", "District Court", "05-04-2023", "Laura Adams", "9845678912"));
        registerCase(new AdvocateDiaryModel(10005, "Divorce Settlement", "Family", "Sophia Miller", "In Progress", "Family Court", "12-05-2023", "Chris Taylor", "9823456789"));
        registerCase(new AdvocateDiaryModel(10006, "Corporate Merger", "Corporate", "Liam Harris", "Closed", "Commercial Court", "18-06-2023", "Emma Carter", "9812348765"));
        registerCase(new AdvocateDiaryModel(10007, "Land Acquisition", "Civil", "Olivia Moore", "Open", "District Court", "22-07-2023", "James Anderson", "9801234567"));

    }

    /**
     * Simulates the loading progress using a SwingWorker thread. Updates a
     * progress bar incrementally and switches to the login screen upon
     * completion.
     */
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                pgBarSplashScreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute(); // Start the worker thread
    }

    // Method to add case data and populate the table
        private void registerCase(AdvocateDiaryModel caseModel) {
        caseList.add(caseModel);
        DefaultTableModel model = (DefaultTableModel) tblCase.getModel();
        model.addRow(new Object[]{
            caseModel.getCaseId(), caseModel.getCaseName(), caseModel.getCaseType(),
            caseModel.getAssignedLawyer(), caseModel.getCaseStatus(),
            caseModel.getCourtName(), caseModel.getFilingDate(),
            caseModel.getClientName(), caseModel.getContactNo()
        });
    }


    /**
     * Switches the application screen to the specified screen name.
     *
     * @param screenName The name of the screen to display.
     */
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    /**
     * Handles the login button action. Validates the username and password
     * input and navigates to the main screen if credentials are correct.
     * Displays appropriate error messages otherwise.
     *
     * @param evt The action event triggered by the login button.
     */
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get the username and password input
        String username = pwdFldLogin.getText();
        //string username=txtFldLoginUsername.getText();
        String password = new String(pwdFldLogin.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblLoginError.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("admin") || !password.equals("admin")) {
            lblLoginError.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblLoginError.setText(""); // Clear any previous error messages
            loadScreen("MainScreen"); // Load the main screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * Handles the logout button action. Clears the login fields and switches
     * back to the login screen.
     *
     * @param evt The action event triggered by the logout button.
     */
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        pwdFldLogin.setText("");
        pwdFldLogin.setText("");
        loadScreen("LoginScreen"); // Load the main screen
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void pwdFldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFldLoginActionPerformed

    private void btnLearnMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLearnMoreActionPerformed
        // TODO add your handling code here:
        pnlSolutions.setSelectedComponent(pnlLegalSolutions);
    }//GEN-LAST:event_btnLearnMoreActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void txtCaseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseNameActionPerformed

    private void txtCaseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIdActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        lblError.setText("");
        txtCaseId.setText("");
        txtCaseName.setText("");
        cmbType.setSelectedIndex(0);
        txtAssignedLawyer.setText("");
        cmbStatus.setSelectedIndex(0);
        txtCourtName.setText("");
        txtFilingDate.setText("");
        txtClientName.setText("");
        txtContactNo.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private boolean isCaseIdExists(int caseId) {
    // Replace 'caseList' with the actual list or database storing  data
    for (AdvocateDiaryModel advocate : caseList) { 
        if (advocate.getCaseId() == caseId) {
            return true; // case ID already exists
        }
    }
    return false; // case ID is unique
}
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        // Get the input data from the UI fields
        String caseId = txtCaseId.getText();
        String caseName = txtCaseName.getText();
        String caseType = cmbType.getSelectedItem().toString();
        String assignedLawyer = txtAssignedLawyer.getText();
        String caseStatus = cmbStatus.getSelectedItem().toString();
        String courtName = txtCourtName.getText();
        String filingDate = txtFilingDate.getText();
        String clientName = txtClientName.getText();
        String contactNo = txtContactNo.getText();

        // Validate the inputs using the ValidationUtil methods
        if (ValidationUtil.isValidCaseId(caseId, lblError) &&
            ValidationUtil.isValidCaseName(caseName, lblError) &&
            ValidationUtil.isValidAssignedLawyer(assignedLawyer, lblError) &&
            ValidationUtil.isValidCourtName(courtName, lblError) &&
            ValidationUtil.isValidFilingDate(filingDate, lblError) &&
            ValidationUtil.isValidClientName(clientName, lblError) &&
            ValidationUtil.isValidContactNo(contactNo, lblError)) {

            lblError.setText("");
            // Create a new CaseModel instance
            int caseIdValue = Integer.parseInt(caseId);
             if (isCaseIdExists(caseIdValue)) { // Call the method to check duplicate IDs
                JOptionPane.showMessageDialog(this, 
                        "Case ID " + caseId + " already exists and cannot be added!", 
                        "Duplicate Entry", 
                        JOptionPane.ERROR_MESSAGE);
            } else{
            
                
            
            
            AdvocateDiaryModel caseModel = new AdvocateDiaryModel(caseIdValue, caseName, caseType, assignedLawyer, caseStatus, courtName, filingDate, clientName, contactNo);

            // Register the case
            registerCase(caseModel);

            // Show a success message
            JOptionPane.showMessageDialog(this, "Case added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
             }

        } else {
            JOptionPane.showMessageDialog(this, "Please enter valid data.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        lblError.setText("");
        int selectedRow = tblCase.getSelectedRow();
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tblCase.getModel();
            model.removeRow(selectedRow);
            caseList.remove(selectedRow);
            JOptionPane.showMessageDialog(this, "Case removed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a case to remove.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblCaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCaseMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblCase.getSelectedRow();
        if (selectedRow != -1) {
            txtCaseId.setText(tblCase.getValueAt(selectedRow, 0).toString());
            txtCaseName.setText(tblCase.getValueAt(selectedRow, 1).toString());
            cmbType.setSelectedItem(tblCase.getValueAt(selectedRow, 2).toString());
            txtAssignedLawyer.setText(tblCase.getValueAt(selectedRow, 3).toString());
            cmbStatus.setSelectedItem(tblCase.getValueAt(selectedRow, 4).toString());
            txtCourtName.setText(tblCase.getValueAt(selectedRow, 5).toString());
            txtFilingDate.setText(tblCase.getValueAt(selectedRow, 6).toString());
            txtClientName.setText(tblCase.getValueAt(selectedRow, 7).toString());
            txtContactNo.setText(tblCase.getValueAt(selectedRow, 8).toString());
        }
    }//GEN-LAST:event_tblCaseMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        // Get the selected row
    int selectedRow = tblCase.getSelectedRow();

    // Check if a row is selected
    if (selectedRow != -1) {
        // Get updated values from text fields
        String caseId = txtCaseId.getText();
        String caseName = txtCaseName.getText();
        String caseType = cmbType.getSelectedItem().toString();
        String assignedLawyer = txtAssignedLawyer.getText();
        String caseStatus = cmbStatus.getSelectedItem().toString();
        String courtName = txtCourtName.getText();
        String filingDate = txtFilingDate.getText();
        String clientName = txtClientName.getText();
        String contactNo = txtContactNo.getText();

        // Validate the inputs using the ValidationUtil methods
        if (ValidationUtil.isValidCaseId(caseId, lblError) &&
            ValidationUtil.isValidCaseName(caseName, lblError) &&
            ValidationUtil.isValidAssignedLawyer(assignedLawyer, lblError) &&
            ValidationUtil.isValidCourtName(courtName, lblError) &&
            ValidationUtil.isValidFilingDate(filingDate, lblError) &&
            ValidationUtil.isValidClientName(clientName, lblError) &&
            ValidationUtil.isValidContactNo(contactNo, lblError)) {
            
            lblError.setText("");

            // Update the selected row in the table
            tblCase.setValueAt(caseId, selectedRow, 0);
            tblCase.setValueAt(caseName, selectedRow, 1);
            tblCase.setValueAt(caseType, selectedRow, 2);
            tblCase.setValueAt(assignedLawyer, selectedRow, 3);
            tblCase.setValueAt(caseStatus, selectedRow, 4);
            tblCase.setValueAt(courtName, selectedRow, 5);
            tblCase.setValueAt(filingDate, selectedRow, 6);
            tblCase.setValueAt(clientName, selectedRow, 7);
            tblCase.setValueAt(contactNo, selectedRow, 8);

            // Update the caseList
            AdvocateDiaryModel updatedCase = new AdvocateDiaryModel(
                Integer.parseInt(caseId), caseName, caseType, assignedLawyer,
                caseStatus, courtName, filingDate, clientName, contactNo
            );
            caseList.set(selectedRow, updatedCase);

            // Show success message
            JOptionPane.showMessageDialog(this, "Case updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Show error message
            JOptionPane.showMessageDialog(this, "Please enter valid data.", "Validation Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // No row selected error
        JOptionPane.showMessageDialog(this, "Please select a case to update.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtCourtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCourtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCourtNameActionPerformed

    private void txtFilingDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilingDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilingDateActionPerformed

    private void txtClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientNameActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void pwdFldLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFldLogin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFldLogin1ActionPerformed

    private void txtFldLoginUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldLoginUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldLoginUsernameActionPerformed

    private void cmbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Retrieve the selected field and sorting order from combo boxes
    String selectedField = cmbSortBy.getSelectedItem().toString();  // For selecting Case ID, ItemName, or Location
    String selectedOrder = cmbSelectionSortingOrder.getSelectedItem().toString();  // For selecting Ascending/Descending

    // Check if a valid field is selected
    if (selectedField.equals("Select Field")) {
        JOptionPane.showMessageDialog(this, "Please select a valid field for sorting (case ID, ItemName, or Location).", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit if no field is selected
    }

    // Determine the sort order: true for descending, false for ascending
  
    boolean isDesc = selectedOrder.equals("Descending");
    
    // Initialize the sorted list variable
    List<AdvocateDiaryModel> sortedList = null;

    // Sort the data based on the selected field
    if (selectedField.equals("CaseID")) {
        // Use SelectionSort for Case ID
        SelectionSort selectionSort = new SelectionSort();
        sortedList = selectionSort.sortByCaseId(caseList, isDesc);
    } else if (selectedField.equals("CaseName")) {
        // Use InsertionSort for CaseName
        InsertionSort insertionSort = new InsertionSort();
        sortedList = insertionSort.sortByItemName(caseList, isDesc);
    } else if (selectedField.equals("Assigend Lawyer")) {
        // Use MergeSort for Assigend Lawyer
        MergeSort mergeSort = new MergeSort();
        sortedList = mergeSort.sortByAssigendLawyer(caseList, isDesc);
    }

    // Check if sortedList is not null before loading it into the table
    if (sortedList != null && !sortedList.isEmpty()) {
        loadListToTable(sortedList);
    } else {
        JOptionPane.showMessageDialog(this, "No data available for sorting.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByActionPerformed
        // TODO add your handling code here:
        // Get user inputs
        String searchValue = txtSearchValue.getText().trim();
        
        String selectedColumn = "Case ID";

        // Validate input
        if (searchValue.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a value to search.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        BinarySearch binarySearch = new BinarySearch();
        // Sort the case list based on the selected column
        sortCaseList(selectedColumn);

        // Perform binary search
        AdvocateDiaryModel result = binarySearch.searchByField(searchValue, selectedColumn, caseList, 0, caseList.size() - 1);

        // Display result
        showSearchResult(result);
    }//GEN-LAST:event_btnSearchByActionPerformed

       private void sortCaseList(String selectedColumn) {
        // Sorting based on selected column
    
        SelectionSort selectionSort = new SelectionSort();
        if (selectedColumn.equals("Case ID")) {
            // Sort in Ascending order
            boolean isDesc = false;
            // Sort the caseList using SelectionSort
            caseList = selectionSort.sortByCaseId(caseList, isDesc);
            
        } 
    }
    
    
    // Display search results
    public void showSearchResult(AdvocateDiaryModel result) {
        if (result == null) {
            JOptionPane.showMessageDialog(null, "No matching record found.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        // Column names
        String[] columnNames = {"Case ID", "Case Name", "Case Type", "Assigned Lawyer", "Case Status", "Court Name", "Filing Date","Client Name", "ContactNo"};

        // Data for table
        Object[][] data = {
            {result.getCaseId(), result.getCaseName(), result.getCaseType(), result.getAssignedLawyer(), result.getCaseStatus(), result.getCourtName(), result.getFilingDate(),result.getClientName(), result.getContactNo()}
        };

        // Table model
        DefaultTableModel tableModel = new DefaultTableModel(data, columnNames);
        JTable table = new JTable(tableModel);

        // Scroll pane
        JScrollPane scrollPane = new JScrollPane(table);
        scrollPane.setPreferredSize(new Dimension(1000, 300));

        // Dialog box
        JOptionPane optionPane = new JOptionPane(scrollPane, JOptionPane.INFORMATION_MESSAGE, JOptionPane.DEFAULT_OPTION);
        JDialog dialog = optionPane.createDialog(null, "Search Result");
        dialog.setSize(1000, 300);
        dialog.setVisible(true);
    }
    
    
    
    private void txtSearchValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchValueActionPerformed

    private void loadListToTable(List<AdvocateDiaryModel>caseList){
        DefaultTableModel model=(DefaultTableModel) tblCase.getModel();
        
        //clear existing rows if needed
        model.setRowCount(0);
        
        //populate the table with advocate data
        caseList.forEach(advocate-> model.addRow(new Object[]{
        advocate.getCaseId(),
        advocate.getCaseName(),
        advocate.getCaseType(),
        advocate.getAssignedLawyer(),
        advocate.getCaseStatus(),
        advocate.getCourtName(),
        advocate.getFilingDate(),
        advocate.getClientName(),
        advocate.getContactNo()
    }));
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvocateDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvocateDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvocateDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvocateDiary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        AdvocateDiary app = new AdvocateDiary();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            app.setVisible(true);
        });

        app.startProgress();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CorporateCasesDescription;
    private javax.swing.JLabel LblTechnologyAndCyberLawCases;
    private javax.swing.JLabel PropertyCasesDescription;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLearnMore;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSearchBy;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbSelectionSortingOrder;
    private javax.swing.JComboBox<String> cmbSortBy;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblCivilCase;
    private javax.swing.JLabel lblCivilCasesDescription;
    private javax.swing.JLabel lblConsumerProtectionCases;
    private javax.swing.JLabel lblConsumerProtectionCasesDescription;
    private javax.swing.JLabel lblContactPart1;
    private javax.swing.JLabel lblContactUs;
    private javax.swing.JLabel lblCorporateCases;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JLabel lblEstateAndProbateCases;
    private javax.swing.JLabel lblEstateProbateCases;
    private javax.swing.JLabel lblHomeScreen;
    private javax.swing.JLabel lblHomeText;
    private javax.swing.JLabel lblHomeTextDescription;
    private javax.swing.JLabel lblInformation;
    private javax.swing.JLabel lblIntellectualPropertyCases;
    private javax.swing.JLabel lblLegalSolutionsImage;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLoadingPageImage;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLoginForgotPwd;
    private javax.swing.JLabel lblLoginImage;
    private javax.swing.JLabel lblLoginMessage;
    private javax.swing.JLabel lblMainBarLogo;
    private javax.swing.JLabel lblMainBarSlogan;
    private javax.swing.JLabel lblPragyaImage;
    private javax.swing.JLabel lblPragyaSub;
    private javax.swing.JLabel lblPragyaTitle;
    private javax.swing.JLabel lblSnehalImage;
    private javax.swing.JLabel lblSnehalSub;
    private javax.swing.JLabel lblSnehalTitle;
    private javax.swing.JLabel lblSuyeshImage;
    private javax.swing.JLabel lblSuyeshSub;
    private javax.swing.JLabel lblSuyeshTitle;
    private javax.swing.JLabel lblTblStudentTitle;
    private javax.swing.JLabel lblTechnologyCaseDescription;
    private javax.swing.JLabel lblWelcomeTitle;
    private javax.swing.JProgressBar pgBarSplashScreen;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlDashboard;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlLegalSolutions;
    private javax.swing.JPanel pnlLoadingScreen;
    private javax.swing.JPanel pnlLoginScreen;
    private javax.swing.JPanel pnlMainBar;
    private javax.swing.JPanel pnlMainScreen;
    private javax.swing.JTabbedPane pnlSolutions;
    private javax.swing.JPasswordField pwdFldLogin;
    private javax.swing.JPasswordField pwdFldLogin1;
    private javax.swing.JScrollPane spTblStudent;
    private javax.swing.JTable tblCase;
    private javax.swing.JTextField txtAssignedLawyer;
    private javax.swing.JTextField txtCaseId;
    private javax.swing.JTextField txtCaseName;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtCourtName;
    private javax.swing.JTextField txtFilingDate;
    private javax.swing.JTextField txtFldLoginUsername;
    private javax.swing.JTextField txtSearchValue;
    private javax.swing.JLabel txtSolutionsTittle;
    // End of variables declaration//GEN-END:variables
}
